module.exports = {
    DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
    ENDPOINT_NOT_FOUND: 'ENDPOINT_NOT_FOUND',
    INVALID_FIELD_VALUE: 'INVALID_FIELD_VALUE',
    REQUIRED_FIELD: 'REQUIRED_FIELD',
    SERVER_ERROR: 'SERVER_ERROR',
    SITE_NOT_FOUND: 'SITE_NOT_FOUND'
};